ApplicationURL=https://www.saucedemo.com
driver=chrome
thread.wait=5
application.load.wait=30
browserMode=HEADED_EXECUTION
APIBaseUrl=https://reqres.in/api/users?page=2
maxRetryCount=2
runmode=local
hubURl=http://192.168.1.8:4444/wd/hub
reasonOfFailure=org.openqa.selenium.TimeoutException,org.openqa.selenium.NoSuchElementException,org.openqa.selenium.remote.UnreachableBrowserException,org.openqa.selenium.WebDriverException,org.openqa.selenium.InvalidElementStateException